/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response from force publish operation
 */
export interface CzzToErpForcePublishResponse { 
    /**
     * Operation success status
     */
    success?: boolean;
    /**
     * Response message
     */
    message?: string;
    /**
     * Message ID from the queue
     */
    messageId?: string;
    /**
     * Entity type
     */
    entityType?: string;
    /**
     * Document ID
     */
    documentId?: string;
}

