/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityIntegrationLogBeanTrace } from './entityIntegrationLogBeanTrace';


export interface EntityIntegrationLogBean { 
    errorUid?: string;
    classId?: string;
    objectId?: string;
    codalm?: string;
    beginDate?: string;
    lastError?: string;
    lastDocumentId?: string;
    lastMessage?: string;
    endDate?: string;
    shopsInvolved?: number;
    lastTraceMessage?: string;
    trace?: EntityIntegrationLogBeanTrace;
}

