/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityIntegrationLogBeanTraceStackTraceInner } from './entityIntegrationLogBeanTraceStackTraceInner';


export interface EntityIntegrationLogBeanTrace { 
    stackTrace?: Array<EntityIntegrationLogBeanTraceStackTraceInner>;
    message?: string;
    localizedMessage?: string;
}

