/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to force publish a ticket to the queue
 */
export interface CzzToErpForcePublishRequest { 
    /**
     * Entity type (tickets, cashjournal)
     */
    entityType: string;
    /**
     * Document ID to republish
     */
    documentId: string;
}

