/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntityConfig { 
    type: string;
    name: string;
    serviceBean: string;
    mapperBean: string;
    mapperMethod: string;
    erpEndpoint: string;
    topic: string;
    dlqTopic: string;
    schedulerCron: string;
    schedulerEnabled?: boolean;
}

